### ISSUE TITLE
Content structure not correct when retrieving page

### ISSUE THREAD

**Issue by csogilvie** [cseeger-epages/confluence-go-api#12]
**Describe the bug**
Apologies, I'm new to Go so may not use the right terminology...

When you try and retrieve a page using `GetContentByID`, it does not appear possible to access the content of the page. This appears to be because the page content is in a view object within the return JSON

**To Reproduce**
1. Create the API object and turn on debug mode
2. Call the code:
`page, err := api.GetContentByID("<id>", goconfluence.ContentQuery{SpaceKey: "<space>", Expand:   []string{"body.view", "version"},})`
3. Examine the JSON returned and observe that there's a `view` object

**Expected behavior**
Access to the page content is possible programatically

**Release version**
Unknown - whatever 'go get' installed

**Additional context**
I've thought about hacking it as:

`// Body holds the storage information
type Body struct {
	Storage Storage `json:"storage"`
	View    Storage `json:"view"`
}`

which seems to work..

**Comment by cseeger-epages** [comment]
i added the `View Storage \`json:"view"\`` and keep the `Storage Storage \`json:"storage"\`` for backwards compatibility

**Comment by cseeger-epages** [comment]
@csogilvie please test if this works for your and close the issue if it does. Thank you very much for your help!

**Comment by conlini** [comment]
@cseeger-epages : adding the view in the Body fails the UpdateContent API with the following error 

_"Maximum number of permitted body entries is 1 but found 2: storage, view"_

pretty printing the Content request, i observed that the zero value of the view object is present always
```
"view":{"value":"","representation":""}}
```

**Comment by cseeger-epages** [comment]
@conlini i fixed this in https://github.com/cseeger-epages/confluence-go-api/commit/731459f97b1e5caf9ac5e87a426238d2c24dd069 see https://github.com/cseeger-epages/confluence-go-api/issues/14

**Comment by cseeger-epages** [comment]
fixed in #14
