### ISSUE TITLE
A new field in a Body struct breaks content update functionality

### ISSUE THREAD

**Issue by iliazlobin** [cseeger-epages/confluence-go-api#14]
**Describe the bug**
The confluence server v7.3.5 doesn't accept a new content body representation **view** in a POST HTTP request.

**To Reproduce**
Include a module dependency in a go.mod:
```
require (
    github.com/cseeger-epages/confluence-go-api v1.2.1
// ...
```
Form a request to create a page:
```
content, err := c.Api.CreateContent(&goconfluence.Content{
    Type:    "page",
    Title:     "page-title",
    Ancestors: []goconfluence.Ancestor{{ID: parentPageId}},
    Body: goconfluence.Body{
        Storage: goconfluence.Storage{
            Value:          "new-content",
            Representation: "storage",
        },
    },
    Version: goconfluence.Version{Number: 1},
    Space:   goconfluence.Space{Key: space},
})
if err != nil {
    return nil, err // <- catch an error
}
```

The request is going to be something like that:
```
{
  "type": "page",
  "title": "page-title",
  "ancestors": [
    {
      "id": "224889851"
    }
  ],
  "body": {
    "storage": {
      "value": "new-content",
      "representation": "storage"
    },
    "view": { // << unexpected new field by a server
      "value": "",
      "representation": ""
    }
  },
  "version": {
    "number": 1
  },
  "space": {
    "key": "my-space"
  }
}
```

Which leads the confluence server to return a 400 error.

[The new **view** body representation field](https://github.com/cseeger-epages/confluence-go-api/blob/v1.2.1/structs.go#L43) has been added in the last commit, which causes this error.

**Thoughts**
According to [the Confluence Java API](https://docs.atlassian.com/ConfluenceServer/javadoc/7.6.0/com/atlassian/confluence/api/model/content/ContentRepresentation.html) ([version 7.3.5](https://docs.atlassian.com/ConfluenceServer/javadoc/7.3.5/com/atlassian/confluence/api/model/content/ContentRepresentation.html) as well), it doesn't feel like the content body accepts the view representation type. If it's really necessary (due to `added view struct + keep storage for backwards compatibility` [commit message](https://github.com/cseeger-epages/confluence-go-api/commit/317a2e67322a210cc2871109c86bb67e689c5977)), it would be wise [to marshal](https://github.com/cseeger-epages/confluence-go-api/blob/v1.2.1/request.go#L64) that conditionally.

**Workaround**
Luckily, [the breaking commit](https://github.com/cseeger-epages/confluence-go-api/commit/317a2e67322a210cc2871109c86bb67e689c5977) adds just this very change. To be able to use the actual version, point to a module's revision in a go.mod:
```
require (
    github.com/cseeger-epages/confluence-go-api v1.1.1-0.20200630082910-1a70940e77ba
// ...
```

**Comment by cseeger-epages** [comment]
hi @iliazlobin i changed the `Body.View` type from `Storage` to `*Storage` and added the `omitempty` tag. On content create/update requests if Body.View is not set it will not be marshaled. I tested your example and it worked for me. Please check if the fix is working correctly.

https://github.com/cseeger-epages/confluence-go-api/commit/731459f97b1e5caf9ac5e87a426238d2c24dd069

**Comment by iliazlobin** [comment]
Thank you, @cseeger-epages. This change resolves the issue
