### ISSUE TITLE
GetContentByID needs expand option

### ISSUE THREAD

**Issue by dsielert** [cseeger-epages/confluence-go-api#2]
**Is your feature request related to a problem? Please describe.**
GetContentByID() is not able to return the content body due to missing expand parameter
**Describe the solution you'd like**
Add optional param, perhaps to function?
**Describe alternatives you've considered**
ContentQuery but doesn't appear you can target by a page ID

**Comment by cseeger-epages** [comment]
hi @dsielert thanks for your ticket, can you give me an example request ?

**Comment by dsielert** [comment]
You literally add &expand=storage.body to the query URL ..

**Comment by cseeger-epages** [comment]
@dsielert sorry for the long wait time, didnt had much time these days but nvm. 
I changed the function signature to `GetContentByID(id string, query ContentQuery) (*Content, error)`
so you can add any query parameter you want to the request. It can now be used same es the GetContent function.

Can you test and confirm if it is working for you ?
