### ISSUE TITLE
Confluence returns 'unknown response status: 400 Bad Request'

### ISSUE THREAD

**Issue by rupertevill** [cseeger-epages/confluence-go-api#5]
**Describe the bug**
I am currently using the method 'CreateContent()' to post pages to Confluence, this works absolutely fine 80% of the time. However, every so often (appears to be random) I receive the error 'unknown response status: 400 Bad Request'. 

**To Reproduce**
```
apiConf, err := goconfluence.NewAPI(confluenceAPIURL, confluenceAcc, confluenceAPIToken)
if err != nil {
    log.Fatal("[ERROR] could not create confluence api conn:", err)
}

Content, err := apiConf.CreateContent(createConfluenceFormBug())
if err != nil {
    log.Println("[ERROR] could not post confluence content:", err)
}

func createConfluenceFormBug() *goconfluence.Content {
	return &goconfluence.Content{
		Type:  "page",
		Title: "test bug page",
		Body: goconfluence.Body{
			Storage: goconfluence.Storage{
				Value: "a bug that I have found...",
				Representation: "storage",
			},
		},
		Version: goconfluence.Version{
			Number: 1,
		},
		Space: goconfluence.Space{
			Key: "TESTBUGS",
		},
	}
}
```
**Expected behavior**
To at least receive some detail on the error.

**Release version**
confluence-go-api@v0.0.0-20190731061204-11651ad4ad41

**Additional context**
Think I have covered everything but happy to add more detail on request :)
Also I appreciate this may simply be an issue with the Confluence API (it doesn't have the best reputation). So happy for you to simply close on this basis.

**Comment by cseeger-epages** [comment]
Hi @rupertevill thanks for opening the issue. Are you using a cloud or self hosted version of the confluence ?

**Comment by rupertevill** [comment]
Hi @cseeger-epages, I'm using a cloud version of confluence.

**Comment by cseeger-epages** [comment]
@rupertevill do you get the error when sending many requests in a row since then you may run into some request limits or is the error happening from time to time when you only do a few requests ?

**Comment by rupertevill** [comment]
We average about 5 requests a day at the moment and we have never (so far) had these requests run concurrently (as only a couple of users drip feed info into this program sporadically throughout the day at the moment). So can't imagine I'm anywhere near any rate limits.

**Comment by cseeger-epages** [comment]
Hm thats tricky. Do you have some logging information from the requests so far by with  Debuging enabled using `goconfluence.SetDebug(true)` ?

**Comment by rupertevill** [comment]
@cseeger-epages I have added this setting and will report back once I observe the error again, hopefully this will add some more detail to the error, thanks for all the help!

**Comment by cseeger-epages** [comment]
your are welcome

**Comment by cseeger-epages** [comment]
I'll close this issue for now. Feel free to reopen it when you find out more about the error
