### ISSUE TITLE
GetChildPages only returns the first 25 pages

### ISSUE THREAD

**Issue by andy-js** [cseeger-epages/confluence-go-api#8]
**Describe the bug**
GetChildPages only returns the first 25 pages.  There's no way to request more than this.

**To Reproduce**
1. Call GetChildPages on a page with more than 25 children.
2. Verify that only 25 pages were returned.

**Expected behavior**
I expect to get all of the child pages.

**Release version**
master.

**Comment by cseeger-epages** [comment]
hi @andy-js thanks for this issue. Your right. I'll take a look into this or feel free to send me a pull request.

**Comment by cseeger-epages** [comment]
@andy-js thank you for finding the bug and also providing a solution :+1:  great work.
